production:
  adapter: postgresql
  encoding: unicode
  database: inviter_production
  pool: 5
  username: inviter
  password: puzzle

development:
  adapter: postgresql
  encoding: unicode
  database: inviter_development
  pool: 5
  username: inviter
  password: puzzle

test:
  adapter: postgresql
  encoding: unicode
  database: inviter_test
  pool: 5
  username: inviter
  password: puzzle